### ISSUE TITLE
Camera-ctl Exposure Bias not working properly

### ISSUE THREAD

**Issue by pavelcucka** [showmewebcam/showmewebcam#94]
When trying to change Exposure Bias in the `camera-ctl` application using arrow keys, it changes by a step of 333 instead of 1. Therefore I am unable to set any meaningful value. Also the default value is 0, while it says it should be 12. 

I am doing this on version v1.70 using Windows 10 and PuTTY. Connected through USB cable. Other options work fine.

**Comment by dgsiegel** [comment]
I know it is confusing, but it is the correct way for the driver. Have a look at this explanation: https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/staging/vc04_services/bcm2835-camera/controls.c#L31-L48

The reason why the default value is 12 instead of 0 is because "0" is the 12th element in that array.

In any case, we can't do much here, but feel free to report this to the Raspberry kernel: https://github.com/raspberrypi/linux/
